Add lockfileVersion check

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -8,6 +8,21 @@ on:
       - main
 
 jobs:
+  assertPackageLockVersion:
+    name: Ensure package-lock lockfileVersion has not changed
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the repository
+        uses: actions/checkout@v2
+      - name: Check package-lock.json
+        run: |
+          file="package-lock.json"
+          expectedVersion="2"
+          lockfileVersion="$(jq -r .lockfileVersion "$file")"
+          if [ "$lockFileVesion" != "$expectedVersion" ]; then
+              echo "$file: lockfileVersion ($lockFileVesion) is invalid (expected: $expectedVersion)"
+              exit 1
+          fi
   cloudFormationSynth:
     name: Run CDK Synthesis
     runs-on: ubuntu-latest
