Add cdk nag
This adds support for running with CDK Nag enabled. It is not a goal to
resolve all of the issues in this PR, just to make ourselves aware of
them.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -50,6 +50,14 @@ jobs:
         run: npm run build
       - name: Synthesize CDK template
         run: cdk synth -c "TicketId=GITHUBWF"
+      - name: Synthesize CDK template with CDK Nag
+        # Errors are allowed here because if there was a true synthesis problem
+        # the previous step would have failed and we would not reach this step.
+        # cdk-nag does not have a "warn-only" mode so this is the best that we
+        # can do.
+        run: cdk synth -c "TicketId=GITHUBWF" || exit 0
+        env:
+          CDK_NAG_ENABLED: 1
       - name: Run test suite
         run: npm test
       - name: Gather artifacts
